---
output: html_document
editor_options: 
  chunk_output_type: console
---

## Correlation between cell hashing and non cell hashing samples

```{r}
# Process each Seurat object (normalization)
normalize_seurat_object <- function(seurat_object){
  normalized_seurat_object <- NormalizeData(seurat_object, normalization.method = "LogNormalize", scale.factor = 10000)
  return(normalized_seurat_object)
}
```

### Plots using mean expression of genes found in all samples

For this plot, I subset each sample to only common genes found in all samples.

```{r}
# Get common genes in compared datasets
UPN23_UPN29_tot_genes <- list(rownames(Seurat_UPN23_filtered@assays$RNA@data),
                              rownames(Seurat_UPN29_filtered@assays$RNA@data),
                              rownames(Seurat_UPN23_UPN29_cellhashing_UPN23_filtered@assays$RNA@data),
                              rownames(Seurat_UPN23_UPN29_cellhashing_UPN29_filtered@assays$RNA@data))
UPN23_UPN29_genes <- Reduce(f = intersect, x = UPN23_UPN29_tot_genes)

UPN23_UPN29_Seurat_list <- list(Seurat_UPN23_filtered, Seurat_UPN29_filtered, 
                                Seurat_UPN23_UPN29_cellhashing_UPN23_filtered, Seurat_UPN23_UPN29_cellhashing_UPN29_filtered)

UPN23_UPN29_Seurat_list_UPN23_UPN29_genes <- lapply(UPN23_UPN29_Seurat_list, subset, features = UPN23_UPN29_genes)

UPN23_UPN29_Seurat_list_UPN23_UPN29_genes_normalized <- lapply(UPN23_UPN29_Seurat_list_UPN23_UPN29_genes, normalize_seurat_object)

na_length <- rep(NA, length(UPN23_UPN29_genes))
mean_df <- data.frame(UPN23_noncellhashing = na_length, UPN29_noncellhashing = na_length,
                      UPN23_cellhashing = na_length, UPN29_cellhashing = na_length)
mean_df$UPN23_noncellhashing <- rowMeans(UPN23_UPN29_Seurat_list_UPN23_UPN29_genes_normalized[[1]]@assays$RNA@data)
mean_df$UPN29_noncellhashing <- rowMeans(UPN23_UPN29_Seurat_list_UPN23_UPN29_genes_normalized[[2]]@assays$RNA@data)
mean_df$UPN23_cellhashing <- rowMeans(UPN23_UPN29_Seurat_list_UPN23_UPN29_genes_normalized[[3]]@assays$RNA@data)
mean_df$UPN29_cellhashing <- rowMeans(UPN23_UPN29_Seurat_list_UPN23_UPN29_genes_normalized[[4]]@assays$RNA@data)
ggpairs(mean_df) + ggtitle("Scatter plot matrix of mean expression of each gene in all cells")
```

<!-- ### Plots using random cells -->

<!-- For the following plots, I chose random cells to draw gene expression. -->

<!-- ```{r} -->
<!-- # Generate 10 random number between 1 and the min number of cell in compared datasets -->
<!-- for(random in sample(1:min(sapply(UPN23_UPN29_Seurat_list, ncol)), 10)){ -->
<!--   na_length <- rep(NA, length(UPN23_UPN29_genes)) -->
<!--   loop_df <- data.frame(UPN23_noncellhashing = na_length, UPN29_noncellhashing = na_length, -->
<!--                         UPN23_cellhashing = na_length, UPN29_cellhashing = na_length, row.names = UPN23_UPN29_genes) -->
<!--   loop_df$UPN23_noncellhashing <- UPN23_UPN29_Seurat_list_UPN23_UPN29_genes_normalized[[1]]@assays$RNA@data[, random] -->
<!--   loop_df$UPN29_noncellhashing <- UPN23_UPN29_Seurat_list_UPN23_UPN29_genes_normalized[[2]]@assays$RNA@data[, random] -->
<!--   loop_df$UPN23_cellhashing <- UPN23_UPN29_Seurat_list_UPN23_UPN29_genes_normalized[[3]]@assays$RNA@data[, random] -->
<!--   loop_df$UPN29_cellhashing <- UPN23_UPN29_Seurat_list_UPN23_UPN29_genes_normalized[[4]]@assays$RNA@data[, random] -->
<!--   print(ggpairs(loop_df) + ggtitle("Scatter plot matrix of expression of each gene randomly selected cells")) -->
<!-- } -->
<!-- ``` -->

```{r}
#Clean memory
rm(UPN23_UPN29_Seurat_list_UPN23_UPN29_genes_normalized,
   UPN23_UPN29_Seurat_list_UPN23_UPN29_genes)
```

