---
output: html_document
editor_options: 
  chunk_output_type: console
---

### UPN23 and UPN29 samples

```{r}
Idents(Seurat_UPN23_UPN29_cellhashing) <- Seurat_UPN23_UPN29_cellhashing$MULTI_ID
Seurat_UPN23_UPN29_cellhashing_norm <- subset(Seurat_UPN23_UPN29_cellhashing, 
                                              idents = c("UPN23-cellhashing", "UPN29-cellhashing"))
Seurat_UPN23_UPN29_cellhashing_norm <- normalize_seurat_object(Seurat_UPN23_UPN29_cellhashing_norm)
Seurat_UPN23_UPN29_cellhashing_norm <- perform_clustering_seurat(Seurat_UPN23_UPN29_cellhashing_norm)
# DimPlot(Seurat_UPN23_UPN29_cellhashing_norm) + ggtitle("UMAP of UPN23 and UPN29 cell hashing colored by cluster")
draw_umap_with_cell_number(Seurat_UPN23_UPN29_cellhashing_norm, grouping = "seurat_clusters") + ggtitle("UMAP of UPN23 and UPN29 cell hashing colored by cluster")
# DimPlot(Seurat_UPN23_UPN29_cellhashing_norm, group.by = "MULTI_ID") + ggtitle("UMAP of UPN23 and UPN29 cell hashing colored by samples")
draw_umap_with_cell_number(Seurat_UPN23_UPN29_cellhashing_norm, grouping = "MULTI_ID") + 
  ggtitle("UMAP of UPN23 and UPN29 cell hashing colored by cluster")
```

```{r}
# Perform on non normalized data
UPN23_UPN29_samples <- c(1,2,3,4)
# Seurat_object_list_clustered[UPN23_UPN29_samples]

Seurat_UPN23_filtered_processed <- Seurat_object_list_clustered[[1]]
Seurat_UPN29_filtered_processed <- Seurat_object_list_clustered [[2]]
Seurat_UPN23_UPN29_cellhashing_UPN23_filtered_processed <- Seurat_object_list_clustered[[3]]
Seurat_UPN23_UPN29_cellhashing_UPN29_filtered_processed <- Seurat_object_list_clustered[[4]]

# p1 <- DimPlot(Seurat_UPN23_filtered_processed) + ggtitle("Non hashed UPN23")
# p2 <- DimPlot(Seurat_UPN29_filtered_processed) + ggtitle("Non hashed UPN29")
# p3 <- DimPlot(Seurat_UPN23_UPN29_cellhashing_UPN23_filtered_processed) + ggtitle("Hashed UPN23")
# p4 <- DimPlot(Seurat_UPN23_UPN29_cellhashing_UPN29_filtered_processed) + ggtitle("Hashed UPN29")

p1 <- draw_umap_with_cell_number(Seurat_UPN23_filtered_processed, grouping = "seurat_clusters") + ggtitle("Non hashed UPN23")
p2 <- draw_umap_with_cell_number(Seurat_UPN29_filtered_processed, grouping = "seurat_clusters") + ggtitle("Non hashed UPN29")
p3 <- draw_umap_with_cell_number(Seurat_UPN23_UPN29_cellhashing_UPN23_filtered_processed, grouping = "seurat_clusters") + ggtitle("Hashed UPN23")
p4 <- draw_umap_with_cell_number(Seurat_UPN23_UPN29_cellhashing_UPN29_filtered_processed, grouping = "seurat_clusters") + ggtitle("Hashed UPN29")

p1
p2
p3
p4

grid.arrange(p1,p2,p3,p4)

p1 <- draw_umap_with_cell_proportion(Seurat_UPN23_filtered_processed, grouping = "seurat_clusters") + ggtitle("Non hashed UPN23")
p2 <- draw_umap_with_cell_proportion(Seurat_UPN29_filtered_processed, grouping = "seurat_clusters") + ggtitle("Non hashed UPN29")
p3 <- draw_umap_with_cell_proportion(Seurat_UPN23_UPN29_cellhashing_UPN23_filtered_processed, grouping = "seurat_clusters") + ggtitle("Hashed UPN23")
p4 <- draw_umap_with_cell_proportion(Seurat_UPN23_UPN29_cellhashing_UPN29_filtered_processed, grouping = "seurat_clusters") + ggtitle("Hashed UPN29")

p1
p2
p3
p4

grid.arrange(p1,p2,p3,p4)


# features <- SelectIntegrationFeatures(object.list = Seurat_object_list_clustered[UPN23_UPN29_samples])
# immune.anchors <- FindIntegrationAnchors(object.list = Seurat_object_list_clustered[UPN23_UPN29_samples], anchor.features = features)
# # this command creates an 'integrated' data assay
# immune.combined <- IntegrateData(anchorset = immune.anchors)
# 
# DefaultAssay(immune.combined) <- "integrated"
# 
# # Run the standard workflow for visualization and clustering
# immune.combined <- ScaleData(immune.combined, verbose = FALSE)
# immune.combined <- RunPCA(immune.combined, npcs = 30, verbose = FALSE)
# immune.combined <- RunUMAP(immune.combined, reduction = "pca", dims = 1:30)
# immune.combined <- FindNeighbors(immune.combined, reduction = "pca", dims = 1:30)
# immune.combined <- FindClusters(immune.combined, resolution = 0.5)
```

```{r}
# FeaturePlot(Seurat_UPN23_filtered_processed, features = (c("PGP", "ABCC1", "GSTK1", "BCL2", "CLIP1", "TGFB1", "LGALS9")))
# 
# res_genes_expressing_cells <- colnames(GetAssayData(Seurat_UPN23_filtered_processed, slot = "data")[,colSums(GetAssayData(Seurat_UPN23_filtered_processed, slot = "data")[c("PGP", "ABCC1", "GSTK1", "BCL2", "CLIP1", "TGFB1", "LGALS9", "CD34", "IL2RA"),])>1])
# DimPlot(Seurat_UPN23_filtered_processed)
# DimPlot(Seurat_UPN23_filtered_processed, cells = res_genes_expressing_cells)
```

```{r}
saveRDS(Seurat_UPN23_UPN29_cellhashing_UPN29_filtered_processed, file = "../../../out/cellhashing_vs_not_cellhashing/R_obj/UPN29_cellhashing_obj_processed.rds")
saveRDS(Seurat_UPN29_filtered_processed, file = "../../../out/cellhashing_vs_not_cellhashing/R_obj/UPN29_obj_processed.rds")
saveRDS(Seurat_UPN23_UPN29_cellhashing_UPN23_filtered_processed, file = "../../../out/cellhashing_vs_not_cellhashing/R_obj/UPN23_cellhashing_obj_processed.rds")
saveRDS(Seurat_UPN23_filtered_processed, file = "../../../out/cellhashing_vs_not_cellhashing/R_obj/UPN23_obj_processed.rds")
```

```{r}
rm(Seurat_UPN23, Seurat_UPN29, Seurat_UPN23_filtered, Seurat_UPN23_UPN29_cellhashing, Seurat_UPN23_UPN29_cellhashing_norm, Seurat_UPN23_UPN29_cellhashing_UPN23,
   Seurat_UPN23_UPN29_cellhashing_UPN23_filtered, Seurat_UPN23_UPN29_cellhashing_UPN29, Seurat_UPN23_UPN29_cellhashing_UPN29_filtered, Seurat_UPN29_filtered)
gc()
```